<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="WebDriver" duration-ms="13054" started-at="2020-08-09T15:29:44Z" finished-at="2020-08-09T15:29:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13054" started-at="2020-08-09T15:29:44Z" finished-at="2020-08-09T15:29:57Z">
      <class name="TestCase.TestNG">
        <test-method status="PASS" signature="launch()[pri:0, instance:TestCase.TestNG@34ce8af7]" name="launch" is-config="true" duration-ms="10834" started-at="2020-08-09T20:59:44Z" finished-at="2020-08-09T20:59:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="VerifyLogin()[pri:0, instance:TestCase.TestNG@34ce8af7]" name="VerifyLogin" duration-ms="999" started-at="2020-08-09T20:59:55Z" finished-at="2020-08-09T20:59:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestCase.TestNG.VerifyLogin(TestNG.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogin -->
        <test-method status="PASS" signature="VerifyTitle()[pri:0, instance:TestCase.TestNG@34ce8af7]" name="VerifyTitle" duration-ms="9" started-at="2020-08-09T20:59:56Z" finished-at="2020-08-09T20:59:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTitle -->
        <test-method status="PASS" signature="VerifyURL()[pri:0, instance:TestCase.TestNG@34ce8af7]" name="VerifyURL" duration-ms="9" started-at="2020-08-09T20:59:56Z" finished-at="2020-08-09T20:59:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyURL -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCase.TestNG@34ce8af7]" name="close" is-config="true" duration-ms="1183" started-at="2020-08-09T20:59:56Z" finished-at="2020-08-09T20:59:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- TestCase.TestNG -->
    </test> <!-- Test -->
  </suite> <!-- WebDriver -->
</testng-results>
