<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36087" started-at="2020-08-09T14:52:58Z" finished-at="2020-08-09T14:53:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36087" started-at="2020-08-09T14:52:58Z" finished-at="2020-08-09T14:53:34Z">
      <class name="TestCase.TestNG">
        <test-method status="PASS" signature="launch()[pri:0, instance:TestCase.TestNG@5419f379]" name="launch" is-config="true" duration-ms="18270" started-at="2020-08-09T20:22:58Z" finished-at="2020-08-09T20:23:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="VerifyLogin()[pri:0, instance:TestCase.TestNG@5419f379]" name="VerifyLogin" duration-ms="2417" started-at="2020-08-09T20:23:16Z" finished-at="2020-08-09T20:23:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestCase.TestNG.VerifyLogin(TestNG.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogin -->
        <test-method status="PASS" signature="VerifyTitle()[pri:0, instance:TestCase.TestNG@5419f379]" name="VerifyTitle" duration-ms="18" started-at="2020-08-09T20:23:19Z" finished-at="2020-08-09T20:23:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTitle -->
        <test-method status="PASS" signature="VerifyURL()[pri:0, instance:TestCase.TestNG@5419f379]" name="VerifyURL" duration-ms="9" started-at="2020-08-09T20:23:19Z" finished-at="2020-08-09T20:23:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyURL -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCase.TestNG@5419f379]" name="close" is-config="true" duration-ms="15357" started-at="2020-08-09T20:23:19Z" finished-at="2020-08-09T20:23:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- TestCase.TestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
